name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Add to sudo groups
      run: sudo usermod -a -G sudo "$USER"
    - name: Print groups
      run: groups

