name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Install wine32
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo dpkg --add-architecture i386
        sudo apt -qq update
        sudo apt install -y --allow-downgrades libpcre2-8-0=10.34-7
        sudo apt install wine32 --fix-broken --install-recommends --install-suggests
