name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        cmake -B build -S . && cmake --build build --target all && ./build/main

